--
-- insert into account(id, account_number, balance, name)
-- VALUES (1, '345696854736', 4300, 'Narek');
--
-- insert into monitor(id, brand, model, price_per_hour, refersh_rate, resolution)
-- VALUES (1, 'Acer', 'BRK100U', 100, 144, '1920x1080');
-- insert into monitor(id, brand, model, price_per_hour, refersh_rate, resolution)
-- VALUES (2, 'HP', 'TRO4903', 140, 244, '4096x2048');
--
-- insert into system_unit(id, cpu, craphics_card, power, price_per_hour, ram)
-- VALUES (1, 'Core i7 9700', 'Nvidia GTX1080', 'High', 200, 16);
-- insert into system_unit(id, cpu, craphics_card, power, price_per_hour, ram)
-- VALUES (2, 'Core i5 9400', 'Nvidia GTX1060', 'Medium', 150, 16);
--
-- insert into workstation(id, workstation_number, computer_club_id, monitor_id, system_unit_id)
-- VALUES (1, 1, 1, 1, 1);
-- insert into workstation(id, workstation_number, computer_club_id, monitor_id, system_unit_id)
-- VALUES (2, 2, 1, 2, 2);
--
-- insert into computer_club(id, address, name)
-- VALUES (1, 'Lesnay 54', 'FirstClub');
